[package]
name = "robust"
version = "0.1.0"
description = "Robust arithmetic utilities"
authors = [
    "The Spade Developers",
    "The GeoRust Developers",
]
edition = "2018"
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
