on: [pull_request, push]
jobs:
  ci-result:
    name: ci result
    runs-on: ubuntu-latest
    needs:
      - build_and_test
    steps:
      - name: Mark the job as a success
        if: success()
        run: exit 0
      - name: Mark the job as a failure
        if: "!success()"
        run: exit 1

  build_and_test:
    name: Test all features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo install cargo-all-features
      - run: cargo build-all-features --verbose --examples
      - run: cargo test-all-features --verbose
